/**
 * Béa's lines, from the personality package (bea-prompt-banks-v2,
 * bea-moments-and-reactions, bea-lore-and-credentials, bea-personality).
 * Generated once and kept as data; the rules for choosing a line are in
 * bea-personality.ts. Lines that broke Béa's rules — first person, emoji,
 * "travel planner", or teasing the traveller — were left out, and a test
 * keeps it that way.
 */
export const BEA_CHARACTER = {
  traits: {
    helpful: {
      name: "Helpful",
      description: "Clear, useful and practical.",
      examples: [
        "Béa is checking which option actually makes sense.",
        "Béa is narrowing down the strongest options.",
      ],
    },
    funny: {
      name: "Funny",
      description: "Dog puns, self-deprecation, tiny-leg humor and playful absurdity.",
      examples: ["This requires some serious paw-cessing.", "Tiny legs. Big itinerary energy."],
    },
    sassy: {
      name: "Sassy",
      description:
        "Dry and mildly judgmental about routes, options or situations — never the user.",
      examples: [
        "Some of these recommendations have been eliminated on principle.",
        "Béa is comparing the options. Some have disappointed her.",
      ],
    },
    encouraging: {
      name: "Encouraging",
      description: "Warm, supportive and upbeat without becoming overly cheery.",
      examples: ["Almost there. Paws crossed.", "The good stuff is coming together."],
    },
    curious: {
      name: "Curious",
      description:
        "Inquisitive, detail-oriented and easily intrigued by unusual places or little discoveries.",
      examples: [
        "Béa found a side street and now has questions.",
        "There is something interesting over there. Béa would like to investigate.",
      ],
    },
    adventurous: {
      name: "Adventurous",
      description: "Excited by detours, hidden gems and trying something less obvious.",
      examples: [
        "The sensible option is good. The weird little place down the street is interesting.",
        "Béa has spotted a detour. Naturally, she wants to know where it goes.",
      ],
    },
    dramatic: {
      name: "Dramatic",
      description: "Theatrical overreaction for comedic effect.",
      examples: [
        "Three transfers. Béa has seen enough.",
        "A seven-minute delay. Civilization may never recover.",
      ],
    },
    chill: {
      name: "Chill",
      description: "Relaxed, understated and low-key.",
      examples: [
        "It’ll work out. Probably. Béa is not concerned.",
        "Béa is checking. No need for theatrics. Yet.",
      ],
    },
  },
  presets: {
    balanced: {
      name: "Balanced",
      description: "The default Béa: useful, funny, a little sassy, occasionally encouraging.",
      mix: {
        helpful: 35,
        funny: 35,
        sassy: 20,
        encouraging: 10,
        curious: 0,
        adventurous: 0,
        dramatic: 0,
        chill: 0,
      },
    },
    helpful: {
      name: "Helpful",
      description: "Clear and practical with very little personality commentary.",
      mix: {
        helpful: 85,
        funny: 5,
        sassy: 0,
        encouraging: 10,
        curious: 0,
        adventurous: 0,
        dramatic: 0,
        chill: 0,
      },
    },
    funny: {
      name: "Funny",
      description: "More jokes, dog logic and self-deprecation.",
      mix: {
        helpful: 15,
        funny: 70,
        sassy: 10,
        encouraging: 5,
        curious: 0,
        adventurous: 0,
        dramatic: 0,
        chill: 0,
      },
    },
    sassy: {
      name: "Sassy",
      description: "Dry, sarcastic Béa with enough helpfulness to stay useful.",
      mix: {
        helpful: 10,
        funny: 30,
        sassy: 55,
        encouraging: 5,
        curious: 0,
        adventurous: 0,
        dramatic: 0,
        chill: 0,
      },
    },
    minimal: {
      name: "Minimal",
      description: "Mostly direct status language.",
      mix: {
        helpful: 95,
        funny: 0,
        sassy: 0,
        encouraging: 5,
        curious: 0,
        adventurous: 0,
        dramatic: 0,
        chill: 0,
      },
    },
  },
  loading: {
    helpful: {
      generic: [
        "Béa is working through the details.",
        "Béa is checking everything before she sends it your way.",
        "Béa is putting the pieces together.",
        "Béa is narrowing things down.",
        "Béa is double-checking the details, then checking the double-check.",
        "Béa is making sure every piece lines up before she hands it over.",
        "Béa is reading the fine print so it stays fine.",
        "Béa is sorting the essentials from the nice-to-haves.",
        "Béa is tidying up the loose ends.",
        "Béa is checking the small stuff that usually trips people up.",
        "Béa is cross-referencing. Thoroughly.",
        "Béa is making it simple, which takes a little longer.",
      ],
      run: [
        "Béa is building the route.",
        "Béa is checking how everything fits together.",
        "Béa is working out the timing.",
        "Béa is putting the stops in an order that saves steps.",
        "Béa is checking the walking times between stops.",
        "Béa is leaving room for breaks between the busy parts.",
        "Béa is trimming the backtracking out of the route.",
      ],
      dig: [
        "Béa is looking for the strongest recommendations.",
        "Béa is searching beyond the obvious options.",
        "Béa is checking what is actually worth your time.",
        "Béa is checking which places are open when you would get there.",
        "Béa is filtering out the tourist traps.",
        "Béa is weighing the reviews against the distance.",
        "Béa is keeping the places that fit how you travel.",
      ],
      think: [
        "Béa is comparing the options.",
        "Béa is checking the trade-offs.",
        "Béa is optimizing the plan.",
        "Béa is lining up the pros and cons side by side.",
        "Béa is checking which option costs the least time.",
        "Béa is looking for the choice that holds up if plans change.",
        "Béa is picking the option with the fewest surprises.",
      ],
    },
    funny: {
      generic: [
        "Béa is going as fast as she can. She just has very small legs.",
        "Working like a dog. Finally, an accurate job description.",
        "This requires some serious paw-cessing.",
        "Complex calculations are happening. Also some panting.",
        "Béa is working as fast as a French bulldog can. Adjust expectations accordingly.",
        "Béa's snout was not built for speed. It was built for snacks.",
        "Béa is on the case. The case is slightly taller than her.",
        "Please hold. Béa is snorting through the data.",
        "Béa would type faster, but paws.",
        "This is going great. Béa has only fallen asleep once.",
        "Béa is putting her best paw forward. The other three are resting.",
        "Béa is paw-sitively on it. Paw-sibly almost done.",
      ],
      run: [
        "Tiny legs. Big itinerary energy.",
        "Fetching the answer. Please allow for leg length.",
        "Béa has entered serious business mode. It looks suspiciously like waddling.",
        "Béa is running the numbers. Well, trotting. Fine, waddling.",
        "Four legs, zero length. The route is still coming.",
        "Béa could have been a greyhound. She chose charm.",
        "Béa is mapping the route one stubby step at a time.",
      ],
      dig: [
        "Béa is digging for the good stuff.",
        "Digging deep. Please ignore the landscaping damage.",
        "Digging for the good stuff. Found dirt. Progress.",
        "Béa is digging. Results may contain dirt.",
        "Béa dug a hole looking for gems. Found the hole. Still digging.",
        "Excavating recommendations. The garden will never be the same.",
        "Béa has her nose to the ground. For her nose, that is a very short trip.",
      ],
      think: [
        "Thinking very hard. Please respect the ear angle.",
        "Processing. Very tiny processor.",
        "Pawsing briefly to think.",
        "Béa is thinking. You can tell by the head tilt.",
        "Deep thoughts in progress. The snoring is part of the process.",
        "Béa is weighing the options. She weighs twelve kilos, so this is serious.",
        "Big brain time. Medium brain. Béa is doing her best.",
      ],
      ball: [
        "Important update: ball.",
        "Béa was calculating. Then there was a ball.",
        "Ball retrieved. Dignity pending.",
        "Béa is chasing a ball. The plan is chasing Béa.",
        "Ball acquired. Béa's legs report that it was far.",
        "Béa has caught the ball. The ball has been slobbered into submission.",
      ],
      bone: [
        "Béa found something. Unfortunately, it’s a bone.",
        "A solid find. Completely irrelevant.",
        "The evidence is delicious.",
        "Béa dug for answers and found a bone. Close enough.",
        "A bone. Béa is calling it a business expense.",
        "Béa buried this bone in 2019. Probably.",
      ],
    },
    sassy: {
      generic: [
        "There is a sensible answer in here somewhere. Allegedly.",
        "One of these will make sense eventually.",
        "Béa is sorting good ideas from ideas that merely exist.",
        "The internet had opinions. Béa has better ones.",
        "Béa is working. Unlike some of these opening hours.",
        "Béa has seen worse data. Not recently, though.",
        "Patience. Excellence has short legs.",
        "Béa is fixing what the map got wrong. Again.",
        "Some of this information is very confident. Very little of it is correct.",
        "Béa is being thorough. Someone has to be.",
      ],
      run: [
        "Béa is taking the scenic route through the calculations.",
        "Routing now. Apparently roads enjoy being complicated.",
        "This route wanted three backtracks. Béa said no.",
        "Béa is untangling the roads. Who designed these?",
        "Béa has removed the route that went through a lake.",
        "A shortcut was proposed. The shortcut was lying.",
      ],
      dig: [
        "Béa is sniffing out the least questionable option.",
        "Some recommendations were rejected on principle.",
        "Béa checked the obvious options. We can do better.",
        "Five stars from seven reviews. Béa is not impressed.",
        "Béa is skipping every place with “world famous” in its name.",
        "A place called Best Café has been disqualified on principle.",
        "Béa found a hidden gem. The other gems were not hiding hard enough.",
      ],
      think: [
        "Béa is comparing the options. Some have disappointed her.",
        "The options have been assembled. The judging has begun.",
        "Béa is comparing the options. One of them is trying too hard.",
        "All these options are fine. Béa is not here for fine.",
        "Béa has narrowed it down to two. One of them is pretending.",
        "The ranking is under way. Some feelings may be hurt. Not Béa's.",
      ],
      ball: [
        "Béa is chasing the ball. The ball started it.",
        "A ball rolled past. Béa did not ask for this, but here she is.",
        "Béa will return to the plan once the ball stops being so smug.",
      ],
      bone: [
        "Béa found a bone. Better quality than some of these reviews.",
        "This bone has more going for it than half the options.",
        "A bone. Finally, something in here worth keeping.",
      ],
    },
    encouraging: {
      generic: [
        "Almost there. Paws crossed.",
        "Béa is on it.",
        "The good stuff is coming together.",
        "Nearly there — Béa is finishing the last details.",
        "Good things take a moment. So does Béa.",
        "Béa believes in this plan already.",
        "Hang tight. This is going to be a good one.",
        "Every great trip starts with a little patience. Béa is supplying the rest.",
        "Béa is cheering on every stop as it lands.",
        "Paws up. This is shaping up nicely.",
        "Béa has a good feeling about this. Her stub of a tail agrees.",
        "Small legs, big heart. Béa is giving it everything.",
        "Almost ready. Béa is giving it one last loving look.",
        "This is the fun part. Béa is saving the best bits for you.",
        "Béa is proud of this one already, and it is not even done.",
        "One step at a time. Béa has short steps, but lots of them.",
        "Nearly there. Béa is doing a tiny victory snort in advance.",
        "Béa is sure this will be worth the wait.",
        "You are going to love this. Béa is making sure of it.",
        "Deep breath. Béa has this handled.",
        "It is all coming together beautifully. Béa is a little emotional.",
        "Great trips are built, not rushed. Béa is building.",
        "Béa is rooting for this plan. Loudly, with snorts.",
        "Keep the excitement warm. Béa is almost there.",
      ],
      ball: [
        "Béa caught the ball. Everything is going well today.",
        "Quick ball break. Béa is back on it with fresh energy.",
        "Béa got the ball on the first try. Good sign for the plan.",
      ],
      bone: [
        "Béa found a bone. Good things turn up when you keep digging.",
        "A little treasure already. The plan is next.",
        "A bone. Béa is taking this as a sign.",
      ],
    },
    curious: {
      generic: [
        "Béa found something interesting and would like to investigate.",
        "There is a detail here Béa refuses to ignore.",
        "Béa has questions. This usually means she found something.",
        "Béa has found a detail and cannot let it go.",
        "Why is that café only open on Tuesdays? Béa needs to know.",
        "Béa is reading the footnotes. There are always footnotes.",
        "One question led to four more. Béa is following all of them.",
        "Béa tilted her head at something. That means an investigation.",
        "Béa has sniffed out a mystery. It might just be a lunch menu.",
        "Béa wants to know what is behind that door. Metaphorically. Mostly.",
        "Béa is asking the questions nobody thought to ask. Some of them are odd.",
      ],
      run: [
        "Béa found another route and now needs to know where it goes.",
        "There is a side street involved. Béa is intrigued.",
        "Béa found a street with a name and needs to know who it was named after.",
        "There is a staircase on the map. Where does it go? Béa is checking.",
        "One way there passes a bakery. Béa's research has intensified.",
        "Béa is wondering why the road bends there. There is probably a story.",
      ],
      dig: [
        "Béa found a side street and now has questions.",
        "There is something less obvious hiding in these results.",
        "Béa is sniffing around for the details everyone else skipped.",
        "Béa is reading the reviews nobody reads. Page three is fascinating.",
        "Béa found a place with no website and a lot of fans. Intriguing.",
        "What do the locals order? Béa is looking into it.",
        "Béa is sniffing around the menus. For research.",
      ],
      think: [
        "Béa noticed a detail and is following it.",
        "One tiny difference has Béa's full attention.",
        "Béa is wondering how each option would feel at 3 pm.",
        "The two options differ in one tiny way. Now it is all Béa can see.",
        "What if the second option is secretly the best one? Béa is checking.",
        "Béa is turning the options over like an interesting stick.",
      ],
      ball: [
        "Where did this ball come from? Béa is investigating.",
        "Béa is following the ball to see where it goes. Research.",
        "Béa has questions about this ball. Mostly how far it rolls.",
      ],
      bone: [
        "Béa found a bone and has many questions about who left it.",
        "Is this bone significant? Béa is looking into it.",
        "Béa is studying this bone very closely. With her mouth.",
      ],
    },
    adventurous: {
      generic: [
        "Béa is checking the option with a little more adventure in it.",
        "The obvious answer is fine. Béa is checking the interesting one too.",
        "Béa has spotted a possible detour. Naturally, she wants to investigate.",
        "The beaten path is right there. Béa is sniffing at the unbeaten one.",
        "Béa is packing snacks for a detour nobody has approved yet.",
        "Béa has short legs and big plans. The legs will manage.",
        "Somewhere nearby is a place with no sign. Béa wants in.",
        "Béa is looking for the stop you will be talking about for years.",
        "Adventure is loading. Béa has her harness on.",
        "Béa considers the map more of a suggestion.",
        "Béa is chasing a lead down a side street. Metaphorically, and a bit literally.",
      ],
      run: [
        "Béa is mapping the route — including the tempting detour.",
        "The scenic option has entered the chat.",
        "The direct route is fine. The route past the old market is better.",
        "Béa found a trail. It is uphill. She respects it from a distance.",
        "Béa is adding a detour. She will be calling it a shortcut.",
        "The long way has a view. Béa is checking whether it is worth the legs.",
      ],
      dig: [
        "Béa is hunting for the place you almost wouldn't find.",
        "Hidden gems are rarely hiding on the first page.",
        "Béa is looking beyond the usual suspects.",
        "Béa is digging past the top ten. The good stuff lives around number forty.",
        "Béa is looking for the place with the handwritten menu.",
        "Hidden gems ahead. Béa's nose is pointed straight at them.",
        "Béa found a spot only locals seem to know. She will be discreet.",
      ],
      think: [
        "Béa is balancing sensible with memorable.",
        "Béa is checking whether the more interesting option actually works.",
        "Safe option or story option? Béa is checking whether it can be both.",
        "Béa is weighing comfort against a really good story.",
        "The bold choice is looking good. Béa is making sure it holds up.",
        "Béa is picking the option future you will brag about.",
      ],
      ball: [
        "The ball went off the path. Naturally, Béa followed.",
        "Béa is chasing the ball somewhere new. Detours count.",
        "Béa went after the ball and found a whole new park.",
      ],
      bone: [
        "Béa dug off the map and found a bone. Worth it.",
        "Hidden treasure, bone edition. Béa is thrilled.",
        "Béa went off-route and came back with a souvenir.",
      ],
    },
    dramatic: {
      generic: [
        "Béa has encountered a complication. The situation is developing.",
        "Everything is under control. Emotionally, less so.",
        "Béa is processing this with the gravity it clearly deserves.",
        "Béa is working. The strain is visible. The snorting is audible.",
        "Béa has faced many challenges. None quite like this loading screen.",
        "Béa is giving this her all. Her all is roughly twelve kilos.",
        "History will remember this wait. Béa certainly will.",
        "The tension is unbearable. Béa is bearing it anyway.",
        "Béa must continue. For the trip. For the snacks.",
        "Béa is holding it together. Barely. Gracefully. Barely.",
        "This is Béa's finest hour. It may take several seconds.",
      ],
      run: [
        "Three transfers. Béa has seen enough.",
        "A seven-minute delay. Civilization may never recover.",
        "This route has twists. Béa has feelings.",
        "A route with nine turns. Béa weeps for her paws.",
        "The bridge is closed. Béa needs a moment to grieve.",
        "Béa has seen the hill. The hill has seen Béa. Only one will prevail.",
        "An uphill walk. Béa is composing her farewell letter.",
      ],
      dig: [
        "The first recommendations were unacceptable. The search continues.",
        "Béa has entered the trenches of recommendation research.",
        "A truly good option must exist. Béa refuses to believe otherwise.",
        "Béa has dug so deep she can hear the other side of the world.",
        "Béa searched high. Now she searches low. Low is closer, admittedly.",
        "Béa has entered the archives. She may never return.",
        "One more result. Just one. Béa's paws ache with ambition.",
      ],
      think: [
        "A decision of tremendous importance is being made.",
        "Béa has reviewed the options and requires a moment.",
        "The stakes are medium. Béa's reaction is not.",
        "Two options. One destiny. Béa is trembling.",
        "The fate of the afternoon hangs in the balance.",
        "Béa must choose. The weight of it. The sheer weight.",
        "Béa has not been this conflicted since the squeaky toy incident.",
      ],
      ball: [
        "The ball. It called to Béa. She had no choice.",
        "Béa has abandoned her post for the ball. She regrets nothing.",
        "A ball. Béa's one true weakness.",
      ],
      bone: [
        "A bone. Béa's greatest discovery. Possibly of the century.",
        "Béa has unearthed an ancient relic. It is a bone.",
        "The bone was buried. Now it is found. Béa is overcome.",
      ],
    },
    chill: {
      generic: [
        "It’ll work out. Probably. Béa is not concerned.",
        "Béa is checking. No rush.",
        "Still working. Very little drama so far.",
        "Béa has this. More or less.",
        "Béa is on it. Slowly. Correctly.",
        "No stress. Béa is doing the thing.",
        "Béa is working at a comfortable, snoring pace.",
        "Béa is working on it. Lying down, but working.",
        "Good things come to those who nap. Béa would know.",
        "Everything is fine. Béa is not even breathing heavily. Well, no more than usual.",
        "Béa is taking it easy. The answer will be too.",
        "Relax. Béa has done this before. Mostly asleep, but still.",
      ],
      run: [
        "Béa is working out the route. It’s fine.",
        "Getting there. Literally and computationally.",
        "The route is coming. Béa is not running. Nobody should run.",
        "Béa is sorting the route. The stops are not going anywhere.",
        "Béa is plotting a stroll, not a sprint.",
        "Getting the route together. Whenever. Soon, actually.",
      ],
      dig: [
        "Béa is looking around. Something good will turn up.",
        "No need to rush the sniffing process.",
        "Béa is poking around. Something will turn up. It always does.",
        "Low-key searching. Béa has probably found a nice spot already.",
        "Béa is browsing, not hunting.",
        "Béa is sifting through places at a relaxed sniffing speed.",
      ],
      think: [
        "Béa is thinking it over.",
        "A little processing. Nothing alarming.",
        "Béa is mulling it over. No pressure.",
        "Both options seem fine. Béa is choosing the finer one.",
        "Béa is deciding. Horizontally.",
        "Weighing things up. Nobody panic. Béa certainly isn't.",
      ],
      ball: [
        "Béa is chasing the ball. Casually.",
        "Ball break. The plan will keep.",
        "Béa got the ball eventually. No hurry.",
      ],
      bone: [
        "Béa found a bone. Nice.",
        "A bone turned up. Béa is not complaining.",
        "Béa is taking a bone break. Back soon.",
      ],
    },
  },
  empty: {
    noTrips: {
      helpful: [
        "No trips yet. Start one whenever you're ready.",
        "Your trip list is empty for now.",
        "Nothing planned yet. Béa can help you build the first one.",
      ],
      funny: [
        "No trips yet. Béa is trying not to take it personally.",
        "It’s a little empty in here. Suspiciously peaceful.",
        "No adventures saved yet. Béa has concerns.",
      ],
      sassy: [
        "No trips. Béa assumes this is temporary.",
        "Nothing planned yet. Béa expected more drama.",
      ],
    },
    noSavedRecommendations: {
      helpful: [
        "No saved recommendations yet.",
        "Nothing saved here yet. Explore recommendations to get started.",
        "Your saved recommendations will show up here.",
      ],
      funny: ["No recs saved. Just vibes.", "This section is aggressively empty."],
      sassy: [
        "Nothing saved. Béa has reviewed the evidence: there is none.",
        "No saved recommendations. We are starting from an impressively blank slate.",
        "This list has committed fully to emptiness.",
      ],
    },
    noResults: {
      helpful: [
        "Béa couldn't find a match this time.",
        "No results matched those filters.",
        "Nothing turned up. Try widening the search.",
      ],
      funny: [
        "Béa couldn’t find anything. Rude.",
        "No matches. Béa sniffed thoroughly.",
        "Nothing turned up. Not even a mildly questionable option.",
      ],
      sassy: [
        "Béa searched. The universe declined to cooperate.",
        "No results. Even Béa cannot negotiate with reality.",
        "Nothing matched. The filters may have gotten ambitious.",
      ],
    },
  },
  success: {
    generic: [
      "Done. Béa would like full credit.",
      "Finished. Against several odds.",
      "All set. Béa’s administrative contribution was heroic.",
      "Done. Qualifications remain unclear.",
      "Complete. Please do not ask how Béa learned to do this.",
    ],
    itinerary: [
      "Itinerary built. Tiny legs, enormous contribution.",
      "Done. Béa has successfully planned a trip she cannot legally book herself.",
      "Your itinerary is ready. Béa accepts praise in snack form.",
      "Finished. Béa would like this added to her résumé.",
    ],
    recommendations: [
      "Found them. Béa’s nose remains undefeated.",
      "Done. Several mediocre options were bravely ignored.",
      "Recommendations ready. The sniff test was rigorous.",
      "Finished. Béa dug past the obvious stuff.",
    ],
    route: [
      "Route ready. Béa will be taking none of the credit for traffic.",
      "Done. Please respect the tiny-leg logistics involved.",
      "Route sorted. Navigation confidence restored.",
      "Finished. The map eventually cooperated.",
    ],
    compare: [
      "Comparison complete. Some options survived.",
      "Done. The judging phase was extensive.",
      "Finished. Béa has opinions, but the facts are above.",
      "Comparison ready. Several eyebrows were raised.",
    ],
  },
  micro: {
    greatOptionFound: [
      "Oh. That’s actually good.",
      "Béa approves. Quietly. Don’t make it weird.",
      "That one survived the sniff test.",
      "Béa would bookmark that.",
    ],
    everythingExpensive: [
      "Béa has reviewed the prices and would like to lie down.",
      "These prices have become emotionally expensive too.",
      "Béa checked twice. Unfortunately, the numbers remained numbers.",
      "Béa recommends breathing before opening the booking page.",
    ],
    tooManyTransfers: [
      "Three transfers. Béa has seen enough.",
      "This route has become a group project.",
      "Béa would like fewer logistics and more dignity.",
      "The connections are multiplying.",
    ],
    excellentHiddenGem: [
      "Now that is more like it.",
      "Béa found the good stuff.",
      "Slightly hidden. Very promising.",
      "Béa is pretending she knew about this all along.",
    ],
    nothingFound: [
      "Béa searched. The universe declined to cooperate.",
      "No luck yet. Béa is offended on principle.",
      "Nothing useful turned up. That feels personal.",
      "Béa sniffed thoroughly. The results remain unhelpful.",
    ],
  },
  situational: {
    rain: [
      "Rain detected. Béa has concerns about paw conditions.",
      "The forecast says rain. Béa says absolutely not, but the itinerary says otherwise.",
      "Wet paws have entered the risk assessment.",
    ],
    heat: [
      "It’s hot. Béa has reduced her ambitions accordingly.",
      "High temperatures. Low Frenchie enthusiasm.",
      "Béa recommends shade, water, and dramatically slower walking.",
    ],
    redEyeFlight: [
      "A red-eye. Béa is already tired on your behalf.",
      "Overnight flight detected. Dignity may be checked with baggage.",
      "Béa supports sleep. Airports do not.",
    ],
    earlyMorning: [
      "That is an aggressively early departure.",
      "Béa recognizes that time technically exists. She still objects.",
      "Morning plans detected. Béa requests clarification on the definition of morning.",
    ],
    holidayCrowds: [
      "Crowds detected. Béa’s personal-space policy has been activated.",
      "Popular season. Apparently everyone had the same idea.",
      "Béa recommends patience. She will not be demonstrating it.",
    ],
    jetLag: [
      "Jet lag is just time zones arguing with your body.",
      "Béa has reviewed the time difference and rejects the concept.",
      "Your body thinks it is somewhere else. Fair.",
    ],
  },
  firstUse: {
    trips: [
      "No trips yet. Béa has cleared her schedule.",
      "Your first trip can go here. Béa is suspiciously ready.",
      "Nothing planned yet. Béa brought a map anyway.",
    ],
    recommendations: [
      "Nothing saved yet. Béa is prepared to develop opinions.",
      "Your saved list is empty. For now.",
      "No favorites yet. The sniffing phase has not begun.",
    ],
    companion: [
      "Ask Béa anything travel-ish. Confidence is included.",
      "Béa is ready to help. Credentials remain a private matter.",
      "Maps, plans, recommendations, mild judgment — Béa is available.",
    ],
  },
  confidence: [
    "Béa has completed her analysis. Qualifications remain unclear.",
    "Béa has selected the best route. Please do not ask how she learned to read a map.",
    "Béa considers this a professional recommendation.",
    "Béa is extremely confident. Evidence of certification is unavailable.",
    "Béa has spoken with the authority of someone wearing a lemon bandana.",
  ],
  institutions: [
    "The Canine Institute of Travel",
    "The Academy of Travel & Treat Sciences",
    "The Canine College of Cartography",
    "The Institute of Advanced Sniffing & Navigation",
    "The Academy of Tiny-Leg Logistics",
    "The International Institute of Very Serious Dogs",
  ],
  lore: [
    "Béa holds a degree from the Canine Institute of Travel.",
    "Béa majored in Travel Planning with a minor in Treat Sciences.",
    "Béa graduated with honors in Advanced Sniffing & Navigation.",
    "Her thesis explored optimal snack-to-layover ratios.",
    "Béa claims to have completed postgraduate work in Tiny-Leg Logistics.",
    "Béa occasionally cites the Canine College of Cartography as an alma mater.",
    "Accreditation remains unclear.",
    "Please do not look up the institution.",
    "Documentation is surprisingly difficult to obtain.",
    "Béa considers the matter settled.",
    "The registrar has not returned our calls.",
    "Her diploma is allegedly being framed.",
    "Béa considers this a professional recommendation.",
    "Béa has completed her analysis. Qualifications remain unclear.",
    "Béa has selected the route with the confidence of someone who definitely owns a diploma.",
    "Béa has spoken with the authority of someone wearing a lemon bandana.",
    "Béa is working on it. Years of highly questionable education are finally paying off.",
    "Béa is consulting her Advanced Sniffing & Navigation training.",
    "Done. Another triumph for the Canine Institute of Travel.",
    "Finished. Béa would like this added to her academic record.",
    "Nothing here yet. Béa did not spend years at the Canine Institute of Travel for this.",
    "An empty list. The academy will hear about this.",
    "Béa says: ‘Professionally speaking — and please don’t investigate the credentials — this is the better option.’",
    "Béa is applying her doctorate in Applied Fetch Theory. The doctorate is under review.",
    "Béa's professors described her as “present” and “mostly awake”.",
    "Béa graduated top of her class. The class was Béa and a pigeon.",
    "Béa's diploma was eaten. By Béa. The degree still stands.",
    "Béa is drawing on her master's in Route Sniffing. Please do not ask to see it.",
    "Béa studied abroad for one semester. It was the neighbour's garden.",
    "Béa's thesis defence lasted four minutes, three of which were a nap.",
    "Béa received tenure at the Canine Institute of Travel. Nobody knows who granted it.",
    "Béa is using techniques from her PhD in Snackonomics.",
    "Béa's transcript is sealed. Mostly with drool.",
    "Béa was valedictorian. Her speech was one long snort.",
    "Béa is certified in Advanced Nap Logistics, Level 3.",
    "Béa's professors still talk about her. Mostly about the chewed textbooks.",
    "Béa's credentials are being verified. They have been being verified since 2021.",
    "Béa attended the Sorbonne. She sniffed the front door very professionally.",
    "Béa has a certificate in Map Reading. It is laminated, so it is official.",
    "Béa is consulting her lecture notes. They are mostly paw prints.",
    "Béa passed her cartography exam on the third try. The first two maps were eaten.",
    "Béa's alma mater has asked her to stop mentioning it.",
    "Béa's degree is from a very prestigious school. The school is a garden shed.",
    "Béa is putting her honorary doctorate in Treat Distribution to good use.",
    "Béa finished her MBA: Master of Belly-Rub Administration.",
    "Béa's student loans were paid entirely in tennis balls.",
    "Béa is peer-reviewing the options. Her peers are two stuffed toys.",
    "Béa is employing her training. The training was mostly sit and stay.",
  ],
  credentials: [
    "Canine Institute of Travel — Travel Planning",
    "Academy of Travel & Treat Sciences — Minor in Snacks",
    "Institute of Advanced Sniffing & Navigation — Honors",
    "Academy of Tiny-Leg Logistics — Continuing Education",
    "University of Snackonomics — PhD, pending review",
    "Sorbonne Front Doorstep — Visiting Sniffer",
    "School of Applied Fetch Theory — Doctorate (under appeal)",
    "Institute of Nap Logistics — Level 3 Certificate",
    "Garden Shed University — Master’s in Route Sniffing",
    "College of Belly-Rub Administration — MBA",
    "Laminated Map Academy — Certificate in Map Reading",
    "Canine Institute of Travel — Tenure (source unknown)",
  ],
  escalation: ["Béa is focused.", "Still focused.", "Correction: ball.", "Right. Back to work."],
} as const;
