-- Share recommendations with another traveller.
--
-- Applied by hand — writing this file does not change the live database alone.
--
-- Design: a share is a SNAPSHOT, not live access to someone's vault. The
-- recommendations policy stays exactly as it is (auth.uid() = user_id FOR ALL),
-- so no future change to that table has to reason about cross-user readers, and
-- no bug there can leak a whole vault. The recipient reads the snapshot through
-- one SECURITY DEFINER function and then inserts copies AS THEMSELVES under the
-- existing policy, so there is no privileged write path at all.
--
-- Mirrors trip_invites: expiry, use caps, revocation, and a rate-limited accept
-- path with an attempts table that has no client policies.

CREATE TABLE IF NOT EXISTS public.reco_shares (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  code text NOT NULL UNIQUE,
  title text,
  note text,
  -- Denormalised on purpose: profiles are readable only by their owner
  -- ("Users read own profile"), so a recipient can never look this up.
  shared_by_name text,
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '30 days'),
  max_uses integer NOT NULL DEFAULT 50,
  use_count integer NOT NULL DEFAULT 0,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.reco_shares DROP CONSTRAINT IF EXISTS reco_shares_code_len;
ALTER TABLE public.reco_shares
  ADD CONSTRAINT reco_shares_code_len CHECK (char_length(code) BETWEEN 8 AND 24);

ALTER TABLE public.reco_shares DROP CONSTRAINT IF EXISTS reco_shares_title_len;
ALTER TABLE public.reco_shares
  ADD CONSTRAINT reco_shares_title_len CHECK (title IS NULL OR char_length(title) <= 120);

ALTER TABLE public.reco_shares DROP CONSTRAINT IF EXISTS reco_shares_note_len;
ALTER TABLE public.reco_shares
  ADD CONSTRAINT reco_shares_note_len CHECK (note IS NULL OR char_length(note) <= 500);

CREATE TABLE IF NOT EXISTS public.reco_share_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  share_id uuid NOT NULL REFERENCES public.reco_shares (id) ON DELETE CASCADE,
  position integer NOT NULL DEFAULT 0,
  -- A copy of the recommendation as it was when shared. Deliberately not a FK
  -- to recommendations: editing or deleting the original must not rewrite or
  -- empty a share someone already received.
  name text NOT NULL,
  city text,
  country text,
  address text,
  category text,
  notes text,
  source text,
  url text,
  lat double precision,
  lon double precision,
  pin_type text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.reco_share_items DROP CONSTRAINT IF EXISTS reco_share_items_name_len;
ALTER TABLE public.reco_share_items
  ADD CONSTRAINT reco_share_items_name_len CHECK (char_length(name) BETWEEN 1 AND 200);

ALTER TABLE public.reco_share_items DROP CONSTRAINT IF EXISTS reco_share_items_notes_len;
ALTER TABLE public.reco_share_items
  ADD CONSTRAINT reco_share_items_notes_len CHECK (notes IS NULL OR char_length(notes) <= 2000);

CREATE INDEX IF NOT EXISTS reco_share_items_share_idx
  ON public.reco_share_items (share_id, position);

CREATE INDEX IF NOT EXISTS reco_shares_owner_idx
  ON public.reco_shares (owner_id, created_at DESC);

-- Rate limit for code guessing. No client policies: only the SECURITY DEFINER
-- reader below writes or reads this, exactly like trip_invite_attempts.
CREATE TABLE IF NOT EXISTS public.reco_share_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  attempted_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS reco_share_attempts_user_recent
  ON public.reco_share_attempts (user_id, attempted_at DESC);

ALTER TABLE public.reco_share_attempts ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.reco_shares TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.reco_share_items TO authenticated;
GRANT ALL ON public.reco_shares TO service_role;
GRANT ALL ON public.reco_share_items TO service_role;
GRANT ALL ON public.reco_share_attempts TO service_role;

ALTER TABLE public.reco_shares ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reco_share_items ENABLE ROW LEVEL SECURITY;

-- Owners manage their own shares. Recipients never select these tables
-- directly — they go through read_reco_share, which is why there is no
-- "anyone with the code can select" policy here.
DROP POLICY IF EXISTS "Owners manage their reco shares" ON public.reco_shares;
CREATE POLICY "Owners manage their reco shares" ON public.reco_shares
FOR ALL TO authenticated
USING (owner_id = auth.uid())
WITH CHECK (owner_id = auth.uid());

DROP POLICY IF EXISTS "Owners manage their reco share items" ON public.reco_share_items;
CREATE POLICY "Owners manage their reco share items" ON public.reco_share_items
FOR ALL TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.reco_shares s
    WHERE s.id = reco_share_items.share_id AND s.owner_id = auth.uid()
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.reco_shares s
    WHERE s.id = reco_share_items.share_id AND s.owner_id = auth.uid()
  )
);

DROP TRIGGER IF EXISTS reco_shares_updated_at ON public.reco_shares;
CREATE TRIGGER reco_shares_updated_at
BEFORE UPDATE ON public.reco_shares
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Read a share by code. Returns one row per item, with the share's own fields
-- repeated, so the client gets everything in a single call.
--
-- Counts one attempt per call and refuses after 20 in 10 minutes, so the code
-- space cannot be walked. Does NOT increment use_count: opening a share is not
-- spending it. claim_reco_share below does that, once the recipient keeps
-- something.
CREATE OR REPLACE FUNCTION public.read_reco_share(_code text)
RETURNS TABLE (
  share_id uuid,
  title text,
  note text,
  shared_by_name text,
  item_id uuid,
  name text,
  city text,
  country text,
  address text,
  category text,
  notes text,
  source text,
  url text,
  lat double precision,
  lon double precision,
  pin_type text
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_share public.reco_shares%ROWTYPE;
  v_recent integer;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Sign in to open a shared list';
  END IF;

  SELECT count(*)::integer INTO v_recent
  FROM public.reco_share_attempts
  WHERE user_id = auth.uid() AND attempted_at > now() - interval '10 minutes';

  IF v_recent >= 20 THEN
    RAISE EXCEPTION 'Too many tries. Wait a few minutes.';
  END IF;

  SELECT * INTO v_share FROM public.reco_shares WHERE reco_shares.code = _code;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'That code does not match a shared list';
  END IF;

  IF v_share.revoked_at IS NOT NULL THEN
    RAISE EXCEPTION 'That list is no longer shared';
  END IF;

  IF v_share.expires_at < now() THEN
    RAISE EXCEPTION 'That share has expired';
  END IF;

  IF v_share.use_count >= v_share.max_uses THEN
    RAISE EXCEPTION 'That share has been used too many times';
  END IF;

  RETURN QUERY
  SELECT
    v_share.id,
    v_share.title,
    v_share.note,
    v_share.shared_by_name,
    i.id,
    i.name,
    i.city,
    i.country,
    i.address,
    i.category,
    i.notes,
    i.source,
    i.url,
    i.lat,
    i.lon,
    i.pin_type
  FROM public.reco_share_items i
  WHERE i.share_id = v_share.id
  ORDER BY i.position, i.created_at;
END;
$$;

-- A STABLE function cannot write, so the attempt is logged separately by the
-- client's RPC wrapper below, which is VOLATILE and does nothing else.
CREATE OR REPLACE FUNCTION public.log_reco_share_attempt()
RETURNS void
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Sign in first';
  END IF;
  INSERT INTO public.reco_share_attempts (user_id) VALUES (auth.uid());
  DELETE FROM public.reco_share_attempts
  WHERE user_id = auth.uid() AND attempted_at < now() - interval '1 day';
END;
$$;

-- Called once the recipient actually keeps something, so use_count measures
-- people who took the list rather than people who looked at it.
CREATE OR REPLACE FUNCTION public.claim_reco_share(_code text)
RETURNS void
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Sign in first';
  END IF;
  UPDATE public.reco_shares
  SET use_count = use_count + 1
  WHERE code = _code
    AND revoked_at IS NULL
    AND expires_at > now()
    AND use_count < max_uses;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.read_reco_share(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.log_reco_share_attempt() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.claim_reco_share(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.read_reco_share(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.log_reco_share_attempt() TO authenticated;
GRANT EXECUTE ON FUNCTION public.claim_reco_share(text) TO authenticated;
