-- Harden trip invites: expiry, single-use by default, revoke, accept rate limit.
-- Applied by hand / MCP — writing this file does not change the live database alone.

ALTER TABLE public.trip_invites
  ADD COLUMN IF NOT EXISTS expires_at timestamptz,
  ADD COLUMN IF NOT EXISTS max_uses integer NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS use_count integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS revoked_at timestamptz;

UPDATE public.trip_invites
SET expires_at = created_at + interval '7 days'
WHERE expires_at IS NULL;

ALTER TABLE public.trip_invites
  ALTER COLUMN expires_at SET DEFAULT (now() + interval '7 days');

CREATE TABLE IF NOT EXISTS public.trip_invite_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  attempted_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.trip_invite_attempts ENABLE ROW LEVEL SECURITY;
-- No client policies: only SECURITY DEFINER accept_trip_invite writes/reads.

CREATE INDEX IF NOT EXISTS trip_invite_attempts_user_recent
  ON public.trip_invite_attempts (user_id, attempted_at DESC);

CREATE POLICY "Members revoke invites"
  ON public.trip_invites
  FOR UPDATE
  TO authenticated
  USING (
    invited_by = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.trip_members m
      WHERE m.trip_id = trip_invites.trip_id AND m.user_id = auth.uid()
    )
  )
  WITH CHECK (
    invited_by = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.trip_members m
      WHERE m.trip_id = trip_invites.trip_id AND m.user_id = auth.uid()
    )
  );

CREATE OR REPLACE FUNCTION public.accept_trip_invite(_code text, _display_name text DEFAULT NULL)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_trip uuid;
  v_id uuid;
  v_expires timestamptz;
  v_revoked timestamptz;
  v_max integer;
  v_uses integer;
  v_recent integer;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Sign in to join a trip';
  END IF;

  INSERT INTO public.trip_invite_attempts (user_id) VALUES (auth.uid());
  SELECT count(*)::integer INTO v_recent
  FROM public.trip_invite_attempts
  WHERE user_id = auth.uid()
    AND attempted_at > now() - interval '10 minutes';
  IF v_recent > 20 THEN
    RAISE EXCEPTION 'Too many invite attempts. Try again later.';
  END IF;

  SELECT id, trip_id, expires_at, revoked_at, max_uses, use_count
  INTO v_id, v_trip, v_expires, v_revoked, v_max, v_uses
  FROM public.trip_invites
  WHERE code = upper(trim(_code));

  IF v_trip IS NULL THEN
    RAISE EXCEPTION 'That invite code does not exist';
  END IF;
  IF v_revoked IS NOT NULL THEN
    RAISE EXCEPTION 'That invite code has been revoked';
  END IF;
  IF v_expires IS NOT NULL AND v_expires < now() THEN
    RAISE EXCEPTION 'That invite code has expired';
  END IF;
  IF v_uses >= v_max THEN
    RAISE EXCEPTION 'That invite code has already been used';
  END IF;

  INSERT INTO public.trip_members (trip_id, user_id, role, display_name)
  VALUES (v_trip, auth.uid(), 'editor', _display_name)
  ON CONFLICT (trip_id, user_id) DO UPDATE
    SET display_name = COALESCE(EXCLUDED.display_name, public.trip_members.display_name);

  UPDATE public.trip_invites
  SET
    use_count = use_count + 1,
    accepted_at = COALESCE(accepted_at, now())
  WHERE id = v_id;

  RETURN v_trip;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.accept_trip_invite(text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.accept_trip_invite(text, text) TO authenticated, service_role;
